// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mqzbuctebbyryptmprkc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1xemJ1Y3RlYmJ5cnlwdG1wcmtjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4MjUwMTQsImV4cCI6MjA2OTQwMTAxNH0.570pZVm90Qgz7URzQthAwlJAzfvgTcu7pTpO6p_mgcw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});